name: MyTestsAction

on:
  push:
    branches:
      - Task_3

jobs:
  initialization:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Test succeded!
